<a href="https://colab.research.google.com/github/handsomekiwi/JupyterPractice/blob/master/IRIS/IRIS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
# load dataset
dataframe = pd.read_csv("https://raw.githubusercontent.com/handsomekiwi/JupyterPractice/master/IRIS/IRIS.csv", header=None)
dataframe


0            1             2            3               4
0    sepal_length  sepal_width  petal_length  petal_width         species
1             5.1          3.5           1.4          0.2     Iris-setosa
2             4.9            3           1.4          0.2     Iris-setosa
3             4.7          3.2           1.3          0.2     Iris-setosa
4             4.6          3.1           1.5          0.2     Iris-setosa
5               5          3.6           1.4          0.2     Iris-setosa
6             5.4          3.9           1.7          0.4     Iris-setosa
7             4.6          3.4           1.4          0.3     Iris-setosa
8               5          3.4           1.5          0.2     Iris-setosa
9             4.4          2.9           1.4          0.2     Iris-setosa
10            4.9          3.1           1.5          0.1     Iris-setosa
11            5.4          3.7           1.5          0.2     Iris-setosa
12            4.8          3.4           1.6          0.2     Iris-setosa
13            4.8            3           1.4          0.1     Iris-setosa
14            4.3            3           1.1          0.1     Iris-setosa
15            5.8            4           1.2          0.2     Iris-setosa
16            5.7          4.4           1.5          0.4     Iris-setosa
17            5.4          3.9           1.3          0.4     Iris-setosa
18            5.1          3.5           1.4          0.3     Iris-setosa
19            5.7          3.8           1.7          0.3     Iris-setosa
20            5.1          3.8           1.5          0.3     Iris-setosa
21            5.4          3.4           1.7          0.2     Iris-setosa
22            5.1          3.7           1.5          0.4     Iris-setosa
23            4.6          3.6             1          0.2     Iris-setosa
24            5.1          3.3           1.7          0.5     Iris-setosa
25            4.8          3.4           1.9          0.2     Iris-setosa
26              5            3           1.6          0.2     Iris-setosa
27              5          3.4           1.6          0.4     Iris-setosa
28            5.2          3.5           1.5          0.2     Iris-setosa
29            5.2          3.4           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
121           6.9          3.2           5.7          2.3  Iris-virginica
122           5.6          2.8           4.9            2  Iris-virginica
123           7.7          2.8           6.7            2  Iris-virginica
124           6.3          2.7           4.9          1.8  Iris-virginica
125           6.7          3.3           5.7          2.1  Iris-virginica
126           7.2          3.2             6          1.8  Iris-virginica
127           6.2          2.8           4.8          1.8  Iris-virginica
128           6.1            3           4.9          1.8  Iris-virginica
129           6.4          2.8           5.6          2.1  Iris-virginica
130           7.2            3           5.8          1.6  Iris-virginica
131           7.4          2.8           6.1          1.9  Iris-virginica
132           7.9          3.8           6.4            2  Iris-virginica
133           6.4          2.8           5.6          2.2  Iris-virginica
134           6.3          2.8           5.1          1.5  Iris-virginica
135           6.1          2.6           5.6          1.4  Iris-virginica
136           7.7            3           6.1          2.3  Iris-virginica
137           6.3          3.4           5.6          2.4  Iris-virginica
138           6.4          3.1           5.5          1.8  Iris-virginica
139             6            3           4.8          1.8  Iris-virginica
140           6.9          3.1           5.4          2.1  Iris-virginica
141           6.7          3.1           5.6          2.4  Iris-virginica
142           6.9          3.1           5.1          2.3  Iris-virginica
143           5.8   

In [16]:
dataset = dataframe.values
import numpy as np
dataset = np.delete(dataset, (0), axis=0)
dataset


array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5', '3.6', '1.4', '0.2', 'Iris-setosa'],
       ['5.4', '3.9', '1.7', '0.4', 'Iris-setosa'],
       ['4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
       ['5', '3.4', '1.5', '0.2', 'Iris-setosa'],
       ['4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
       ['5.4', '3.7', '1.5', '0.2', 'Iris-setosa'],
       ['4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
       ['4.8', '3', '1.4', '0.1', 'Iris-setosa'],
       ['4.3', '3', '1.1', '0.1', 'Iris-setosa'],
       ['5.8', '4', '1.2', '0.2', 'Iris-setosa'],
       ['5.7', '4.4', '1.5', '0.4', 'Iris-setosa'],
       ['5.4', '3.9', '1.3', '0.4', 'Iris-setosa'],
       ['5.1', '3.5', '1.4', '0.3', 'Iris-setosa'],
       ['5.7', '3.8', '1.7', '0.3', 'Iris-setosa'],
       ['5.1', '3.8', '1

In [19]:
X = dataset[:,0:4].astype(float)
Y = dataset[:,4]
X


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [20]:
Y


array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [23]:
from sklearn.preprocessing import LabelEncoder
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
encoded_Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [26]:
from keras import utils as np_utils
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)
dummy_y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0