<a href="https://colab.research.google.com/github/handsomekiwi/JupyterPractice/blob/master/IRIS/IRIS_knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
# load dataset
dataframe = pd.read_csv("https://raw.githubusercontent.com/handsomekiwi/JupyterPractice/master/IRIS/IRIS.csv", header=None)
#dataframe. add tab to find function
dataframe.head() #.head gives the first 5 row


0            1             2            3            4
0  sepal_length  sepal_width  petal_length  petal_width      species
1           5.1          3.5           1.4          0.2  Iris-setosa
2           4.9            3           1.4          0.2  Iris-setosa
3           4.7          3.2           1.3          0.2  Iris-setosa
4           4.6          3.1           1.5          0.2  Iris-setosa

In [73]:
dataset = dataframe.values
import numpy as np
dataset = np.delete(dataset, (0), axis=0)
dataset[0:5]

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5', '3.6', '1.4', '0.2', 'Iris-setosa']], dtype=object)

In [75]:
X_input = dataset[:,0:4].astype(float)
X_input[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [76]:
Y_answer = dataset[:,4]
Y_answer

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [0]:
#neighbors 用5
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors =5)
knn.fit(X_input,Y_answer)
predictions = knn.predict(X_input)

In [90]:
#用混淆矩陣來看結果 3 2是錯的
confusion_matrix(Y_answer,predictions)


array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  2, 48]])

In [92]:
knn = KNeighborsClassifier(n_neighbors =1)#neghbors 用1
knn.fit(X_input,Y_answer)
predictions = knn.predict(X_input)
confusion_matrix(Y_answer,predictions)

array([[50,  0,  0],
       [ 0, 50,  0],
       [ 0,  0, 50]])